### ISSUE TITLE
Could not use the example.

### ISSUE THREAD

**Issue by romklao** [ryansh100/bricklink-api#1]
Hi,

I try to use your code to retrieve data from Bricklink but it does not work. Therefore I use the code following code and it works.

`'use strict';

const express = require('express');
const app = express();

const Client = require('bricklink-api').Client;
console.log('hi', Client);
const ItemType = require('bricklink-api').ItemType;
const bricklink = new Client({
    "consumer_key": "<ConsumerKey>",
    "consumer_secret": "<ConsumerSecret>",
    "token": "<TokenValue>",
    "token_secret": "<TokenSecret>"
  });

app.get('/part/:id', function(req, res) {
   bricklink.getCatalogItem('PART', req.params.id)
  .then(function(part){
    res.json(part)
  }); 
})`

**Comment by ryansh100** [comment]
Looks like it may be an error on ItemType since I see that you used "PART" in place of the object property.

**Comment by ryansh100** [comment]
See the updated documentation for usage. You will need to upgrade to the 1.1.0 package.
