### ISSUE TITLE
Failed request should reject

### ISSUE THREAD

**Issue by janmisek** [ryansh100/bricklink-api#3]
Hello 

First of all thanks for the lib. It helped me alot, as it implements signing. But I have one issue with failed requests.

Failed requests are `console.log`ed and resolved on line: https://github.com/ryansh100/bricklink-api/blob/b87910b91843f9e1429e67b71854aa70626ae99e/src/client.js#L73

Then it is impossible to get error reason.

I am overcoming the issue using own client. But I think it would be usefull to resolve and reject with whole bricklink data

**Comment by ryansh100** [comment]
Would you be interested in opening a request that rejects with a proper error?

**Comment by ryansh100** [comment]
This should be resolved now.
