### ISSUE TITLE
Including error information in thrown exception 

### ISSUE THREAD

**Issue by ofir-shapira-como** [ryansh100/bricklink-api#35]
Hi @ryansh100, thanks for the library, would you be able to add more data about errors from BrickLink? might want to throw an object instead of a string.

https://github.com/ryansh100/bricklink-api/blob/a40e0807c7c042be0c794fca65728aec84592a4a/src/client.js#L94-L107

e.g.
```
const error = {
          resourceURL: resourceURL,
          responseMetadata: payload.meta,
        }
```

Would you accept a PR for that?

**Comment by ryansh100** [comment]
I would prefer to make an extension of an Error, since it's bad practice to reject with non-Error objects.

I am definitely open to accepting a pull request though, thank you!

**Comment by ofir-shapira-como** [comment]
Cool, so I'll create a PR with an Error object, something like `BrickLinkError` that will extend `Error` and will contain some data we get from BrickLink (status code, etc...), is this OK?

**Comment by ryansh100** [comment]
Yep, we agree on the approach.

Perhaps add a test that it rejects with our expected `BrickLinkError` shape. (i.e. - `expect(error.responseMetadata.code).toBe(500)`)

https://github.com/ryansh100/bricklink-api/blob/main/src/client.js.

There is a commit hook that generates documentation, so don't be surprised if there's a huge diff on commit.

**Comment by ofir-shapira-como** [comment]
Opened a PR -  https://github.com/ryansh100/bricklink-api/pull/36

The interesting files (rest are docs and .gitignore)
![image](https://user-images.githubusercontent.com/24762112/172779687-f769e81e-9c0e-403d-ba64-0a15073ae24f.png)

Thanks

**Comment by ofir-shapira-como** [comment]
Merged in https://github.com/ryansh100/bricklink-api/pull/36
