### ISSUE TITLE
Client.Send method do not catch errors when called with a callback function

### ISSUE THREAD

**Issue by Atepir** [ryansh100/bricklink-api#37]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `brickbase-bricklink-api@1.1.5` for the project I'm working on.

### Description of the issue
I was trying to make a web interface using ExpressJs and Bricklink-API. 
The problem is errors handling.
When an error is sent from bricklink api, it is not caught in case there is a callback to the **Client Send method**.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/brickbase-bricklink-api/dist/client.js b/node_modules/brickbase-bricklink-api/dist/client.js
index 85b4a64..deba093 100644
--- a/node_modules/brickbase-bricklink-api/dist/client.js
+++ b/node_modules/brickbase-bricklink-api/dist/client.js
@@ -111,7 +111,7 @@ var Client = exports.Client = function () {
       });
 
       if (req.callback) {
-        promise.then(req.callback);
+        promise.then(req.callback).catch(req.callback);
       }
       return promise;
     }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by ryansh100** [comment]
Can you provide an example of how Client.Send used directly?
