### ISSUE TITLE
Error requesting prices

### ISSUE THREAD

**Issue by SvenSommer** [ryansh100/bricklink-api#4]
Hey ryansh100,
currently request `getPriceGuide`-request seems to be broken.
It leads to the following error:
```
node_modules/bricklink-api/src/client.js:68
let data = JSON.parse(body);
^
SyntaxError: Unexpected token < in JSON at position 0
at JSON.parse (<anonymous>)

```
Did the Bricklink Api, announce some changes?
Do you have time to investigate?

**Comment by SvenSommer** [comment]
I think I found the issue.
I polled the price guide in a loop to get all the information about a specific set. After several successful responses. The Bricklink api responds with:
`<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>`
which causes the app to crash.

**Comment by SvenSommer** [comment]
I will try to solve this, by adding small waiting intervals between the different `getPriceGuide ` calls.

**Comment by ryansh100** [comment]
Did you happen to get an idea for how quickly you were getting throttled?

**Comment by SvenSommer** [comment]
I turned out the number of parallel requests needed to be limited to a maximum number of 5.
